### ISSUE TITLE
Link for Ventura down

### ISSUE THREAD

**Issue by UlyssesZh** [yusufklncc/Hackintosh-for-All-Computers#2]
Google Drive says that the file does not exist.

**Comment by ImranKKG** [comment]
Download links for Ventura, Monterey And Big Sur are not working. Please provide download links of MAC OS

**Comment by Johnfohwhfowhf** [comment]
Use idm for downloading.

**Comment by Johnfohwhfowhf** [comment]
Each and every os is downloading.

**Comment by yusufklncc** [comment]
I updated the whole README.
