### ISSUE TITLE
There is no download links 

### ISSUE THREAD

**Issue by 4everbacon** [yusufklncc/Hackintosh-for-All-Computers#5]
Hi. Download links for Ventura, Monterey And Big Sur are missing. It just sends me to the main page

**Comment by Johnfohwhfowhf** [comment]
You can download it straight from idm. No bullshit.

**Comment by UlyssesZh** [comment]
> You can download it straight from idm. No bullshit.

First, this is an existing issue and is not *bullshit*. Second, IDM is a paid software and only has Windows version, and you should not force others to use a paid software or a paid OS.

**Comment by yusufklncc** [comment]
I updated the whole thing.
