### ISSUE TITLE
Downloading links for ventura, monterey, bigsur not working

### ISSUE THREAD

**Issue by cs59** [yusufklncc/Hackintosh-for-All-Computers#7]
it used to work yesterday and today when am trying to download ventura image again, then it started showing me error
OneDrive - 
This item might not exist or is no longer available
This item might have been deleted, expired, or you might not have permission to view it. Contact the owner of this item for more information.
![Screenshot (1)](https://github.com/yusufklncc/Hackintosh-for-All-Computers/assets/68501788/dd9272c4-cf15-4dcd-94e5-c3916f31bd40)

**Comment by DishKing** [comment]
Same

**Comment by DishKing** [comment]
I have comet lake and I would really like to use ventura

**Comment by deepanshpandey** [comment]
https://dijital.link/macos-imajlar-yusufklncc

**Comment by yusufklncc** [comment]
I updated all image links, images and README.
